### ISSUE TITLE
Does this plugin integrate/sync with the ISPConfig billing module?

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wc-invoice-pdf#11]
My question is that if you have both this plugin and the billing module add-on enabled in ISPConfig, will there be any conflicts or are both designed to work hand in hand? Will there be any conflict of interests?

**Comment by ole1986** [comment]
Since this plugin was primarily focused on a free alternative to the ISPConfig billing module with integration into Wordpress there should not be any problem running both.

But keep in mind when a woocommerce order is placed (containing a Webspace product for instance) the wc-invoice-pdf plugin will be triggered to create the website in ISPConfig3.

*This could then also trigger the ISPConfig3 billing module.**

**Comment by tawandakembo** [comment]
Gotcha. Makes sense. Thank you

**Comment by ole1986** [comment]
As a side note, with the upcoming version (1.5.2 i assume) this plugin is completely isolated from the wp-ispconfig3 plugin. So if you do not need any ISPConfig3 related functions the wp-ispconfig3 can safely be deactivated/removed from wordpress. 

So you profit only from the (recurring) invoice feature for a Woocommerce Order.
