### ISSUE TITLE
ERROR on checkout page -> Sorry, your session has expired. Return to shop

### ISSUE THREAD

**Issue by oleh1** [ole1986/wc-invoice-pdf#16]
WooCommerce Version 3.8.0
When switching to checkouts, an error appears - "Sorry, your session has expired. Return to shop"

**Comment by ole1986** [comment]
Is this reproducible using a specific product or generally?

**Comment by oleh1** [comment]
Generally

**Comment by ole1986** [comment]
When you disable the plugin, does the error persist?

**Comment by oleh1** [comment]
No, the error disappears

**Comment by ole1986** [comment]
Since this plugin does not affect the session expiration directly I am wondered why this error occurs.

Therefore it is necessary to ask you some more questions:

* Does the message appear when no product is added into the checkout procedure?
* Does the message appear before or after placing the order?
* When a product is necessary to reproduce, which product type has been chosen?

**Comment by oleh1** [comment]
Here I have a clean WordPress with WooCommerce and your plugin, you can check
https://task-test.pp.ua/
login - task-test-admin
password - S$wBL)HVm#3&A0Hipui9iVtC

**Comment by ole1986** [comment]
The plugin was designed to remove all non-subscribed products from the checkout procedure once a subscription product is added to the cart.

Subscription products are those which are shipped with this plugin, E.g. Webspace.

For some reason a product (E.g. of type Simple Product) will always be removed. No matter if a subscription product is added to the cart.

I will need to fix this and put it on high prio.

Thank you for reporting.

**Comment by oleh1** [comment]
Thanks
