### ISSUE TITLE
multiple client template

### ISSUE THREAD

**Issue by acaleroni** [ole1986/wc-invoice-pdf#31]
How can I configure several products with different client templates? in configuration it only allows one

**Comment by ole1986** [comment]
Actually a product does not relate to a client.
So you can usually "register" to several users.

Can you come up with some more details on what the goal is?

**Comment by acaleroni** [comment]
Create 4 products each linked to a ispconfig client template that limits your use of mailbox, subdomains, database, etc.  But in the configuration panel it only allows linking to a general template with the produc webservices, instead of doing it by product

**Comment by ole1986** [comment]
ATM we only support a webspace product with a default client template (configured through the settings).

This product can be customized with webspace related properties (like harddisk quota, traffic quota, SSL, ...)

So, this issue is a request of additional products to pass mailbox and database configuration to ISPConfig when buying the products

**Comment by acaleroni** [comment]
It is right, it's possible?

**Comment by ole1986** [comment]
IspConfig3 will no longer be supported.
But additional Woocommerce products, like Webspace for subscription and service products will be still available
