### ISSUE TITLE
Payment Reminder of deleted Customers

### ISSUE THREAD

**Issue by smilebasti** [ole1986/wc-invoice-pdf#32]
As i was testing this plugin i created random Users but i deleted them later.

Now i am getting an daily E-Mail: Payment reminder. (Attached)
I even deleted the plugin and reinstalled it.

Is there a file to maybe delete these manually?
Thanks
![image](https://user-images.githubusercontent.com/60941345/80865911-67065600-8c8c-11ea-8909-778bec0ebfcf.png)

**Comment by ole1986** [comment]
Are these invoices still available in the `WC Invoices` -> `Invoices` list?
Also check the Trash view.

You may then permanently remove these invoices so you wont get the reminder anymore.

**Comment by smilebasti** [comment]
There is nothing listed. Nothing in All and Trash.

**Comment by ole1986** [comment]
This line expected to have the invoices in the list and not marked as paid or deleted

https://github.com/ole1986/wc-invoice-pdf/blob/master/model/invoice-task.php#L60

So it might be that due to the removal of it customer that the list does not show them... But they still exists.

You may need to resolve it yourself by careful cleaning up the wc-invoice table

**Comment by smilebasti** [comment]
Ok thanks. Should have worked
